name: CI
on:
  push:
    branches: [ "develop", "main" ]

env:
  node_version: 20

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        submodules: true
        token: ${{ secrets.GH_PAT }}

    - name: Move .env files from scheduler to root
      run: mv BE-secret/scheduler/.env* ./

    - name: Install pnpm
      uses: pnpm/action-setup@v4

    - name: Use Node.js ${{ env.node_version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.node_version }}
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install

    - name: Build
      run: pnpm run build

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      run: aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY_URI }}

    - name: Docker build & push to ECR (develop)
      if: github.ref == 'refs/heads/develop'
      run: docker build -t ${{ secrets.ECR_REGISTRY_URI }}:dev -f Dockerfile --push .

    - name: Docker build & push to ECR (production)
      if: github.ref == 'refs/heads/main'
      run: docker build -t ${{ secrets.ECR_REGISTRY_URI }}:prod -f Dockerfile --push .

    - name: Server Deploy (develop)
      if: github.ref == 'refs/heads/develop'
      run: |
        aws ssm send-command \
          --document-name "AWS-RunShellScript" \
          --instance-ids "${{ secrets.EC2_INSTANCE_ID }}" \
          --parameters commands='[
            "aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY_URI }}",
            "cd /root",
            "[ $(docker ps --filter 'publish=1024' -q | wc -l) -gt 0 ] && docker stop $(docker ps --filter 'publish=1024' -q)",
            "[ $(docker images -q ${{ secrets.ECR_REGISTRY_URI }}:dev | wc -l) -gt 0 ] && docker rmi ${{ secrets.ECR_REGISTRY_URI }}:dev",
            "docker pull ${{ secrets.ECR_REGISTRY_URI }}:dev",
            "docker run --rm -d -p 1024:1024 --name writely-scheduler -e NODE_ENV=development ${{ secrets.ECR_REGISTRY_URI }}:dev"
          ]' \
          --comment "Deploying Docker container (develop)"
          
    - name: Server Deploy (production)
      if: github.ref == 'refs/heads/main'
      run: |
        aws ssm send-command \
          --document-name "AWS-RunShellScript" \
          --instance-ids "${{ secrets.EC2_INSTANCE_ID_PROD }}" \
          --parameters commands='[
            "aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY_URI }}",
            "cd /root",
            "[ $(docker ps --filter 'publish=1024' -q | wc -l) -gt 0 ] && docker stop $(docker ps --filter 'publish=1024' -q)",
            "[ $(docker images -q ${{ secrets.ECR_REGISTRY_URI }}:prod | wc -l) -gt 0 ] && docker rmi ${{ secrets.ECR_REGISTRY_URI }}:prod",
            "docker pull ${{ secrets.ECR_REGISTRY_URI }}:prod",
            "docker run --rm -d -p 1024:1024 --name writely-scheduler -e NODE_ENV=production ${{ secrets.ECR_REGISTRY_URI }}:prod"
          ]' \
          --comment "Deploying Docker container (production)"